--------------------------------------------------------
--  Fichier créé - dimanche-mars-30-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CENTRE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LOAY"."CENTRE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CENTRE
--------------------------------------------------------

  CREATE TABLE "LOAY"."CENTRE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(255 BYTE), 
	"DIRECTEUR" VARCHAR2(20 BYTE), 
	"FACILITIES" VARCHAR2(255 BYTE), 
	"STATUS" NUMBER, 
	"CAPACITE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "LOAY"."EMPLOYE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NUMERO_TELEPHONE" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"DATE_DEMBAUCHE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ETUDIANT
--------------------------------------------------------

  CREATE TABLE "LOAY"."ETUDIANT" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXAM
--------------------------------------------------------

  CREATE TABLE "LOAY"."EXAM" 
   (	"ID_EXAMEN" NUMBER, 
	"DATE_EXAMEN" DATE, 
	"HEURE_EXAMEN" NUMBER, 
	"DUREE" NUMBER, 
	"MATIERE" VARCHAR2(50 BYTE), 
	"CENTRE_EXAMEN" VARCHAR2(50 BYTE), 
	"COLUMN1" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORMATION
--------------------------------------------------------

  CREATE TABLE "LOAY"."FORMATION" 
   (	"ID" NUMBER, 
	"SUJET" VARCHAR2(50 BYTE), 
	"DATE_FORMATION" DATE, 
	"HEURE" VARCHAR2(10 BYTE), 
	"DUREE" NUMBER, 
	"STATUT" VARCHAR2(20 BYTE), 
	"ID_EMPLOYE" NUMBER, 
	"ID_CENTRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATERIEL
--------------------------------------------------------

  CREATE TABLE "LOAY"."MATERIEL" 
   (	"ID" NUMBER, 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"LOCALISATION" VARCHAR2(20 BYTE), 
	"DISPONIBILITE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into LOAY.CENTRE
SET DEFINE OFF;
Insert into LOAY.CENTRE (ID,NOM,ADRESSE,DIRECTEUR,FACILITIES,STATUS,CAPACITE) values ('2',null,null,null,null,null,null);
Insert into LOAY.CENTRE (ID,NOM,ADRESSE,DIRECTEUR,FACILITIES,STATUS,CAPACITE) values ('3',null,null,null,null,null,null);
REM INSERTING into LOAY.EMPLOYE
SET DEFINE OFF;
REM INSERTING into LOAY.ETUDIANT
SET DEFINE OFF;
REM INSERTING into LOAY.EXAM
SET DEFINE OFF;
REM INSERTING into LOAY.FORMATION
SET DEFINE OFF;
Insert into LOAY.FORMATION (ID,SUJET,DATE_FORMATION,HEURE,DUREE,STATUT,ID_EMPLOYE,ID_CENTRE) values ('921000000','c',to_date('01/01/00','DD/MM/RR'),'00:00','0','Prévue','0','0');
Insert into LOAY.FORMATION (ID,SUJET,DATE_FORMATION,HEURE,DUREE,STATUT,ID_EMPLOYE,ID_CENTRE) values ('650097152','c',to_date('01/01/00','DD/MM/RR'),'00:00','0','Prévue','0','0');
Insert into LOAY.FORMATION (ID,SUJET,DATE_FORMATION,HEURE,DUREE,STATUT,ID_EMPLOYE,ID_CENTRE) values ('0','d',to_date('01/01/00','DD/MM/RR'),'00:00','0','Prévue','0','0');
REM INSERTING into LOAY.MATERIEL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ETUDIANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOAY"."ETUDIANT_PK" ON "LOAY"."ETUDIANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CENTRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOAY"."CENTRE_PK" ON "LOAY"."CENTRE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOAY"."EXAM_PK" ON "LOAY"."EXAM" ("ID_EXAMEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MATERIEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOAY"."MATERIEL_PK" ON "LOAY"."MATERIEL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOAY"."EMPLOYE_PK" ON "LOAY"."EMPLOYE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CENTRE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LOAY"."CENTRE_TRG" 
BEFORE INSERT ON CENTRE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CENTRE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "LOAY"."CENTRE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ETUDIANT
--------------------------------------------------------

  ALTER TABLE "LOAY"."ETUDIANT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."ETUDIANT" ADD CONSTRAINT "ETUDIANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIEL
--------------------------------------------------------

  ALTER TABLE "LOAY"."MATERIEL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."MATERIEL" MODIFY ("COLUMN1" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."MATERIEL" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."MATERIEL" MODIFY ("DISPONIBILITE" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."MATERIEL" ADD CONSTRAINT "MATERIEL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CENTRE
--------------------------------------------------------

  ALTER TABLE "LOAY"."CENTRE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."CENTRE" ADD CONSTRAINT "CENTRE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXAM
--------------------------------------------------------

  ALTER TABLE "LOAY"."EXAM" MODIFY ("ID_EXAMEN" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EXAM" MODIFY ("DATE_EXAMEN" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EXAM" MODIFY ("HEURE_EXAMEN" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EXAM" MODIFY ("DUREE" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EXAM" MODIFY ("MATIERE" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EXAM" MODIFY ("CENTRE_EXAMEN" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EXAM" MODIFY ("COLUMN1" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EXAM" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EXAM" ADD CONSTRAINT "EXAM_PK" PRIMARY KEY ("ID_EXAMEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "LOAY"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EMPLOYE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EMPLOYE" MODIFY ("NUMERO_TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EMPLOYE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EMPLOYE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EMPLOYE" MODIFY ("DATE_DEMBAUCHE" NOT NULL ENABLE);
  ALTER TABLE "LOAY"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORMATION
--------------------------------------------------------

  ALTER TABLE "LOAY"."FORMATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
